services:
  - type: web
    name: quran-app-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd QuranMemoryApp2
      python manage.py collectstatic --noinput
    startCommand: |
      cd QuranMemoryApp2
      python manage.py migrate --noinput
      gunicorn quran_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: quran_backend.settings
      - key: DATABASE_URL
        fromDatabase:
          name: quran-app-db
          property: connectionString

databases:
  - name: quran-app-db
    databaseName: quran_app
    user: quran_user
    plan: free
