services:
  - type: web
    name: quran-app-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn quran_backend.wsgi:application --chdir QuranMemoryApp2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: quran_backend.settings
