# Generated by Django 5.2.5 on 2025-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_populate_mkamal_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorization',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memorization',
            name='review_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
