# Generated by Django 5.2.5 on 2025-09-01 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_memorization_last_review_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorization',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='memorization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memorization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MemorizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ayah', models.IntegerField()),
                ('end_ayah', models.IntegerField()),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('review', 'review'), ('complete', 'complete'), ('other', 'other')], default='update', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('memorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.memorization')),
            ],
            options={
                'verbose_name': 'Memorization Log',
                'verbose_name_plural': 'Memorization Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
